# Generated by Django 4.2.1 on 2023-06-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caja',
        ),
    ]
