# Generated by Django 4.2.1 on 2023-06-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('contenido', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('categorias', models.ManyToManyField(to='caja.categoriacaja')),
            ],
            options={
                'verbose_name': 'caja',
                'verbose_name_plural': 'cajas',
            },
        ),
    ]
