# Generated by Django 4.2.1 on 2023-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaCaja',
            new_name='Categoria',
        ),
        migrations.AlterField(
            model_name='caja',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cajas'),
        ),
    ]
