# Generated by Django 4.2.1 on 2023-06-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='imagen',
            field=models.ImageField(upload_to='nosotros'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
